language: bash
services: docker

env:
  - VARIANT=apache
  - VARIANT=apache-php7
  - VARIANT=fpm
  - VARIANT=fpm-php7

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "$VARIANT"
  - slash='/'; image="joomla:${VARIANT//$slash/-}"

script:
  - docker build -t "$image" .
  - ~/official-images/test/run.sh "$image"

after_script:
  - docker images

# vim:set et ts=2 sw=2:
